# Data Consolidation  Example (ver 2023-02-16)
## At times your data will be contained in many different files. In this exercise, you will read the data from several files, consolidate that data, and write them to a single file.
You will learn how to construct a list of file names. You will use a for loop to read the data from each file in the list and an if statement to perfom some tasks only in the first iteration of the loop. As you do that the data will be consolidated into an array variable. You will learn about formatted output. You will then write that consolidated data to a new file as formatted numbers. 

Each input file you are give represents a separate measurement set: y measured as a function of x. One row for each x-y pair. The x values in each of the 6 files are the same in this example, but you should verify that yourself. The output file will have all the y values grouped with the appropriate x. For example each row will have the x value followed by the 6 y values: x, y1, y2, y3, y4, y5, y6. The input files in this example are DOS tab delimited .txt format. The output file will be in commas delimited .csv format.

## How to perform this assignment and submit it for credit

Begin with the assignment (this file) and the data files provided in the same sciserver directory. 

The tasks below describe exercises in coding for you to perform in the code cell immediately following the task markdown cell. In some cases a code block is provided to get you started. Code snippets may also be provided. You can copy them into the code cell as a starting point. Generally copy and paste of that code is not enough to get credit for a task. You will need to modify and expand that code. Read through the text and follow what you are asked to do. To get full credit you will need to provide evidenvce that you did the exercise. In some tasks lead you through building up a code block. You do not need to show all the steps, the state of the code after you have done the exercise is sufficient. You need to have the successful pisplay output in addition to the code.

Submission. You will use an archive program to create a zip file containing your final Jupyter notebook with the input and ouput files. You will then submit the .zip file to canvas.

## TASK 1: Create the list of file names. (1 point)
Your input data files all have the pattern 'data_set_xx_yy.txt', where xx is a number unique to you and yy is a sequence number differentiating the datasets. You will create the list of your files as an array of strings. A string is a variable type that contains text. Creat a variable called `file_list`. In the example below, I have filled in the first two files. You will need to edit this statement to match the names of your actual files names and add four more lines to expand the array to include all six file names. Note in my example, I place one file name on each line. The array begins with `[` and ends with `]`. This is done for readability. Having the list of names aligned vertically makes it easier to compare the files names and make sure you have the names typed correctly. Learning to write code that is readable, is a big part of learning to code. It will aso save you time tracking down typos. 

```
file_list = [
    'data_set_xx_y1.txt', 
    'data_set_xx_y2.txt',
]
```

Use the '+' sign in the menu above to insert a code cell below this markdown cell to write the code for this exercise. We will use `file_list` in the rest of this assignment.

How many file names are in `file_list`? You should know that answer, but is it best practice to read that information directly from the array variable. We will use the `len()` method to read the number of elements in the array and assign that to `num_files`. We will then print the length. If it is not six, you will need to figure out why and fix that before proceeding.

```
num_files = len(file_list)
print(num_files)
```


In [1]:
file_list = [
    'data_set_01_01.txt', 
    'data_set_01_02.txt',
    'data_set_01_03.txt',
    'data_set_01_04.txt',
    'data_set_01_05.txt',
    'data_set_01_06.txt',
]
num_files = len(file_list)
print(num_files)

6


## Task 2: Checking the file list using the for loop (1 point)

Test that the file names have been stored correctly in the array by printing each name out in sequence using a for loop. The for loop uses a loop counter that increments after each iteration of the loop, the integer `ii` is the loop counter in this example. The loop repeats the code within the loop until the loop counter is equal to or greater than last element in the range object `range(num_list)`, which is a type of array. For example range(6) is basically [0, 1, 2, 3, 4, 5, 6]. On the first iteration of the loop, ii = 0. On the final iteraton ii = 5. 

*Note:*

*1) Indenting in Python is more than cosmetic, it is important to the structure of the code. How does Python determine which statements are part of the 'for block' in the loop? Python does not have a statement marking the end of the loop like other languages. All code after the `for` statement that has a greater indent is part of the loop. The end of the 'for block' is signaled by the return to the same or lower level of indent as the `for`.*

*2) The `for` statement ends with a colon!*


```
for ii in range(num_files):
    print(file_list[ii])
```
    
*Note: I like to use 'i j, k, l, m, n' as loop counter variables. However in some languages, 'i' or 'j' is defined as sqrt(-1). AND the single letters are conveneint to use for other variables, as needed. It is a common mistake to clobber a variable like 'i' by using it in a loop. So I have adopted the practice of using 'ii, jj, kk, ll, mm, nn' as loop variables instead.*

In [2]:
for ii in range(num_files):
    print(file_list[ii])

data_set_01_01.txt
data_set_01_02.txt
data_set_01_03.txt
data_set_01_04.txt
data_set_01_05.txt
data_set_01_06.txt


## Task 3: Basic file reading (1 point)
Before we get into the nitty gritty of reading the numerical values from the files, we will read the first five lines from each file and print them to the screen. If we can read each file and their headers to show the files are different, we can move on.

Your data files begin with a header consisting to three lines of text labeling the data. Headers are useful to tell you what the data is. An unlabeled block of numbers can cause embarrassing mistakes. 

For your code you will need to construct a for loop to read and display the first five lines of each file. I will give you the part of the example that goes inside that for loop. Before you do that, test the block of code on a single file. If that doesn't work, putting it inside a loop will not improve that much.

It is important to understand what these statements are doing as this is common to most languages.
1. The `open` statement creates an object called a *file handle*. Here that file handle is assigned to the variable `file`, but we could have chosen `BoomerSooner` just as well. The parameter `'r'` tells Python that the file is open for reading and that writing to the file is not allowed. So you cannot accidently over write it.
2. `readline()` is a method of the file handle, invoked on the file we just opened as `file.readline()`. Recall this could have been `BoomeSooner.readline()`. `line = file.readline()` reads the contents of the line as a string and assigns it to `line`. 
3. In the `for jj` loop, we read one line at a time and print it to the display.
4. Each time `line = file.readline()` is executed, a new line is read. How does that work? One of the attributes of the file handle is a file pointer, a number that keeps track of where we are in the file. The method `readline()`, after reading a line, advances the file pointer to the beginning of the next line. In this exercise we don't need to worry about the file pointers, because that it handeled by the read/write methods we are using. But there are other methods that independently operate on the file pointer, e.g. moving it to the beginning, the end of the file, or forward and backward by a specified number of bytes.
5. `close` is a method telling python AND your operating system that you have released the file. If two different programs are trying to manipulate a file at the same time, the results can be unexpected. To prevent that, opening the file tells the OS that the file is in use. Closing the file tells the OS you are finished with it and then another program can use it. It is very important to close the file when you are done. For example, trying to open a file that is already open generally will give an error.

```
file = open(file_list[0],'r')
for jj in range(5):
    line = file.readline()
    print(line)
file.close()
```

Once you place the above code inside the loop over files names, you will need to edit something in the code block above to make that work...

Note that the x values for all your files are identical, but the y valuse are not. That is by design in this exercise.

Why is there an blank line after each line displayed? Reed the next section to fine out.

In [14]:
for ii in range(num_files):
        file = open(file_list[ii],'r')
        for jj in range(num_files):
            line = file.readline()
            print(line)
        file.close()

An exponentially decaying sine wave on a constant background

data set 1

x_data	y_data

 20.0	  1.42

 20.7	  1.85

 21.5	  2.53

An exponentially decaying sine wave on a constant background

data set 2

x_data	y_data

 20.0	  1.46

 20.7	  1.98

 21.5	  2.30

An exponentially decaying sine wave on a constant background

data set 3

x_data	y_data

 20.0	  1.07

 20.7	  2.19

 21.5	  2.45

An exponentially decaying sine wave on a constant background

data set 4

x_data	y_data

 20.0	  1.46

 20.7	  2.19

 21.5	  2.12

An exponentially decaying sine wave on a constant background

data set 5

x_data	y_data

 20.0	  1.32

 20.7	  1.79

 21.5	  2.26

An exponentially decaying sine wave on a constant background

data set 6

x_data	y_data

 20.0	  1.06

 20.7	  2.20

 21.5	  2.51



## Task 4: Understandng the text file. (1 point)

The most efficient way to process data from a file, is to read the entire file into an array variable and then parse the array. This is what we will do in this example.

First let's discuss how data is stored in a text file.

We will use a very general way to read data from a text file. In general, text files contain fields of ASCII text arranged in rows and columns. These fields are separated by special characters called delimiters. 
> What is ASCII? It is the most common way text characters, such as the letters of the text in this document, are encoded into binary. For historical reasons, this is called extended ASCII. Each byte in the file represents a single charcter. There are 256 possible characters. Some are not printable, such as the carraige return, line feed, and tab characters. The full table can be found here: 
<a href="https://www.ascii-code.com/">extended ASCII table</a>

The end of the rows are delimited by the sequence of the `carriage return` and `line feed` characters in windows/DOS and the `line feed` character in linux. Usually the end of row delimiter is handled automatically by most functions intended to read text files. After this example we will not worry about the row delimiters in our work. These terms come from the typewriter. It is a good idea to understand these because they are ubiquitous. 

You just saw the effect of these end of row delimeters (AKA line delimeters) in the example above. The `readline()` method included the end of line delimeters in the string assigned to the `line` variable. The `print()` method already advances the display to the next line. Including the end of like delimeters in the string, casue it to advance two lines.

In Python the `carraige return` (or simply *retrun*) is denoted by a two character combination `\r` and the `line feed` (*next line*) is denoted `\n`. *Note that the `\` designates the start of a two character combination denoting a special caracter.*

Try this example

```
print('hellohello')
print('hello')
```

Now insert one and two `\n`'s between the two hello's: `'hello\nhello'`and `'hello\n\nhello'`

The column delimiter is commonly a `comma`, `space`, or `tab` character. However it could be anything you wish. The restriction is that it must not be a character that could appear in the field of ASCII text. For example, the characters 0123456789.+-eE would be likely appear in the ASCII representation of numeric values and therefore would be poor choices as a delimiter. 

Your data files are tab delimited. The first three rows are a header, containing a destription of the data set and identify the rows. 


In [17]:
# 1st example
print('hellohello')
print('hello')
# One \n
print('hello\nhello')
# Two \n
print('hello\n\nhello')

hellohello
hello
hello
hello
hello

hello


## Task 5: Read the data from the text files and consolidate into one array. (2 points)

We will use the `numpy` method `loadtxt` to read the entire file into an array variable we arbitarily call data. This method converts the ASCII representation of the numbers (strings) to floating point variables (numbers). Each text field between the column delimiters yields a number. A text file with 4 numbers per row and 25 rows will give a 25x4 array. 

We direct `loadtxt` to skip the first three rows: `skiprows=3`
And set the delimiter to tab: `delimiter='\t'`

As in task 3, we will start by reading one file. In the final code, you will loop over all the files. 

We will collect the data from all six files into one large array. We know that we will have six y values for each x value. We also know in advance that the x valuse are in the same sequence in each of the six files, which simplifies the task. W need to determine how many data rows are in the files and then create a array that is the correct size to accumulate the data.

Here we have include the loop index ii, that will be used when we loop over the file names. But for developing the code, we have not included the loop yet. Instead, we set ii = 0 to simulate the first iteration through the loop.

*I have included notes on array indexing shortcuts at the end of this exercise that will help understand the syntax.

It is important to understand what each new part of the code is doing.
1. `import numpy as np` imports numpy, which contains the method `loadtext'.
2. `data = np.loadtxt(fname, skiprows=3, delimiter='\t')` reads the data in the text file into the array `data`. We told loadtext it to skip the first three rows (the header) (`skiprows=3`) and that the column delimeter is a tab (`delimiter='\t'`). Note that numpy loadtext does not require us to first open the file and close it in the end. That is all handled by loadtext, which is a higher level function. Note thet we had to import numpy for this. The open, readline, and close are native components of python. Also observe how loadtext works. It's once and done. The open and the close is all part of it.
3. `data_size = np.shape(data)` returns the dimensions of data. `data_size` is a two element array. `data_size[0]` is the number of rows. `data_size[1]` is the number of columns. Use `print(data_size)` as a diagnostic to check the values.
4. `np.zeros((data_size[0],data_size[1]+num_files-1))` creates an array of zeros the exact size we need. It is preferred to calculate the dimension from the data instead of *hard coding*. For example we know we need 7 columns, but we calulate that from `data_size[1]` and `num_files`.
5. `out_data[:,0] = data[:,0]` We load the x data into the first column.
6. `out_data[:,ii+1] = data[:,1]` We load the y data from the first file into the second column. We calculate that using the loop index ii so that it will increment the column for each file.
7. Finally we write the array to the display to verify that we have written the x values to the first column and the y values to the second.


```
import numpy as np

ii = 0
fname = file_list[ii]
data = np.loadtxt(fname, skiprows=3, delimiter='\t')
data_size = np.shape(data)
print(data_size)
out_data = np.zeros((data_size[0],data_size[1]+num_files-1))
out_data[:,0] = data[:,0]
out_data[:,ii+1] = data[:,1]
print(out_data)
```

We are almost ready to loop of the file names. However some statement in the code block only need to be done the first time through to set things up. The statements we only need to do once are:

```
data_size = np.shape(data)
out_data = np.zeros((data_size[0],data_size[1]+num_files-1))
out_data[:,0] = data[:,0]
```

It won't hurt to do the first and last six times, but redefining out_data would erase the data from all the previous iterations.
We can fix this using an `if` statement.

`if ii == 0:` will execute the statements inented below it only then ii = 1.
Note two details. 1) In the `if` statement `==` is used because this is a compare, not an assignment. 2) There must be a colon at the end of `if ii == 0:`

You will need to be careful with indenting to make sure the for loop and the if block ar nested properly.

In the final code block, do not use the `print(data_size)`, that is on;ly diagnostic. The `print(out_data)` also needs to be after the file loops so it shows the final, filled array.


In [27]:
import numpy as np

data_size = np.shape(data)
out_data = np.zeros((data_size[0],data_size[1]+num_files-1))
out_data[:,0] = data[:,0]

for ii in range(num_files):
        fname = file_list[ii]
        data = np.loadtxt(fname, skiprows=3, delimiter='\t')
        out_data[:,ii+1] = data[:,1]
        
print(out_data)

[[ 2.00e+01  1.42e+00  1.46e+00  1.07e+00  1.46e+00  1.32e+00  1.06e+00]
 [ 2.07e+01  1.85e+00  1.98e+00  2.19e+00  2.19e+00  1.79e+00  2.20e+00]
 [ 2.15e+01  2.53e+00  2.30e+00  2.45e+00  2.12e+00  2.26e+00  2.51e+00]
 [ 2.22e+01  2.38e+00  2.46e+00  2.31e+00  2.00e+00  2.41e+00  2.45e+00]
 [ 2.30e+01  1.86e+00  1.90e+00  1.90e+00  1.72e+00  1.85e+00  1.61e+00]
 [ 2.37e+01  1.15e+00  8.20e-01  9.40e-01  8.20e-01  8.50e-01  1.21e+00]
 [ 2.45e+01  3.20e-01  1.30e-01  4.40e-01 -1.00e-02  1.90e-01  1.60e-01]
 [ 2.52e+01 -4.00e-01 -3.90e-01 -6.90e-01 -5.40e-01 -5.60e-01 -4.60e-01]
 [ 2.60e+01 -9.60e-01 -9.40e-01 -1.17e+00 -9.70e-01 -9.90e-01 -1.23e+00]
 [ 2.67e+01 -1.45e+00 -1.26e+00 -1.03e+00 -1.34e+00 -1.21e+00 -1.40e+00]
 [ 2.74e+01 -9.70e-01 -1.22e+00 -1.09e+00 -9.90e-01 -9.00e-01 -8.60e-01]
 [ 2.82e+01 -6.00e-01 -8.00e-01 -8.00e-01 -7.40e-01 -4.50e-01 -7.50e-01]
 [ 2.89e+01  2.00e-01 -9.00e-02  2.60e-01 -3.00e-02 -1.10e-01 -8.00e-02]
 [ 2.97e+01  8.10e-01  7.40e-01  6.80e-01  9.20e-01

## Task 6: Understanding formatted output. (2 points)

The task of writing our data to the csv file requires that we understand how floating point numbers are represented as text. We will control that using formatted output. Specifically, we will use the fixed point format, meaning the number of decimal places is fixed and it is not scientific notation. For example, 3.14 and 237.9 are examples of fixed point formats.

Lets examine this in more detail. We will use -$\pi$ which is available in numpy as `np.pi` as out test number. Experiment with this block of code. The second line creates a ruler so you can see the effect of the formating. The caret appears every 5 characters.

```
print('{:8.4f}'.format(-np.pi))
print('||||^||||^||||^||||^')
```

The output will look like this:

```
-3.1416
||||^||||^||||^||||^
```

Observe:
- There are 4 decimal places.
- The last digit is in the 8th column
- There is one space before the minus sign
- The number is rounded to the last decimal place. ( $\pi$ = 3.141592...)

Let's parse the format specifier `8.4f`. The *8* is the width of the text field, *4* is the number of decmal places, and *f* specifies fixed point. In order to display any number on the screen, Python must convert it to ASCII text. The format specifier instructs Python how to do that. In this example, the ASCII string is 8 characters wide, with 4 decimal places. To determine the required width for fixed point, you need to also know something about the size of the numbers. For -$\pi$, you will need one column for the digit on the left of the decimal point, a column for the sign, another for the decimal point, and the 4 decimal places. For a total of 7 columns. That is the minimum width required. In this example we have an extra column on the left. Try changing the format spcifier to `7.4f` and then `8.5f` 

If you choose a width too narrow, Python seems to just expand the width to the minimum required. Some languages enforce the width you chose. In those cases `6.4f` would be two narrow to display `-3.1416` and the output would be a field filled with *#* `######`. Excel does this when the cell width is too narrow to display the number in the cell. **For us, the advantage to choosing a width that works for all our numbers is that the decimals in the csv file will be aligned for easy reading. You will get full credit too!**

<u>The number of decimal places needed for the x and y values.</u> We will need to use the same number of decimal places for the x values that were present in the original files. And the decimal places for the y values with match the m=numer in the y valuse. The x and y values in general will not have the same number of decimals. Look back at the results from task 3 where you displayed the first five lines of each data file.

<u>The width needed for the x and y values.</u> To do that we simply need to find the number with the largest magnitude in the x and in the y values. In this example we find the maximum of the absolute value of the x values (first column in `out_data` and the y values (last 6 colums in `out_data`). The numpy functions, max and absolute, function on the entire array or the portion specified.

```
print(np.max(np.absolute(out_data[:,0])))
print(np.max(np.absolute(out_data[:,1:6])))
```

For my data the largest magnitude is 93.2 for x and 3.3 for y. My 6 input files had 1 decimal place for x and 2 for y. How wide a field do I need in my case? I need two digits to the left of the decimal plus the sign, the decimal, and the one decimal place (-xx.x) for a width of 5. The format specifier for the x data will be `5.1f`. In y, the format specifier wil be `5.2f`. *Note: In fixed point, you always need at least two columns on the left of the decimal. One for the sign, even if you don't think you need it and a leading zero, even if the largest magnitude is less than 1 (e.g. -0.45).*

Let's unpack the rest of the format statement: `'{:8.4f}'.format(-np.pi)`
`'{:8.4f}'` Is the output string. `{:8.4}` will be replaced by `-np.pi`. To see how this works, try this code:

```
print('example: -pi={:7.4f}!'.format(np.pi))
print('||||^||||^||||^||||^||||^')
```

The output should look like:

```
example: -pi = -3.1416!
||||^||||^||||^||||^||||^
```

The `{:8.4}` in the text string is replaced by `-3.1416`.

If we include more format specifiers in the string, each will be replaced by the values in the variables in the order they appear. This statement will display the first x and y values in `out_data`.

**You will need to modify the format specifiers in this example to match the requirments of your data.**

```
print('x = {:5.1f}, y = {:5.2f}'.format(out_data[0,0], out_data[0,1]))
print('||||^||||^||||^||||^||||^')
```

To generate the comma delimited csv file, we need to insert commas between the numbers and terminate the line with the carriage-return line-feed combination. 

```
ii=0
print('{:5.1f},{:5.2f},{:5.2f},{:5.2f},{:5.2f},{:5.2f},{:5.2f}\r\n'.format(*out_data[ii,:]))
```

In this an example the first line of data on `out_data` is displayed. The `*` in `*out_data[ii,:]` instructs Python to fill the format placeholders with the values in the array along the `:` dimension (row in this case). This is short hand for 

```
print('{:5.1f},{:5.2f},{:5.2f},{:5.2f},{:5.2f},{:5.2f},{:5.2f}\r\n'.format(out_data[ii,0],out_data[ii,1],out_data[ii,1],out_data[ii,3],out_data[ii,4],out_data[ii,5],out_data[ii,6])))
```

The shorthand is less cumbersome.



In [42]:
# Exploring Formatted Output 
print('{:8.8f}'.format(-np.pi))
print('||||^||||^||||^||||^')


# Largest X & Y Value 
print(np.max(np.absolute(out_data[:,0])))
print(np.max(np.absolute(out_data[:,1:6])))

# Formatted Output in String
print('example: -pi={:8.4f}!'.format(np.pi))
print('||||^||||^||||^||||^||||^')


# Output Formatted Data
print('x = {:5.2f}, y = {:5.2f}'.format(out_data[0,0], out_data[0,1]))
print('||||^||||^||||^||||^||||^')


# Shorthand 
ii=0
print('{:5.1f},{:5.2f},{:5.2f},{:5.2f},{:5.2f},{:5.2f},{:5.2f}\r\n'.format(*out_data[ii,:]))

-3.14159265
||||^||||^||||^||||^
90.0
2.53
example: -pi=  3.1416!
||||^||||^||||^||||^||||^
x = 20.00, y =  1.42
||||^||||^||||^||||^||||^
 20.0, 1.42, 1.46, 1.07, 1.46, 1.32, 1.06



## Task 7: Write the consolidated data to a formatted csv file. (2 points)
The final task is writing the data we have consolidated into a comma delimited csv file. 

We are almost ready to write the comma delimited csv file. We need a header describing the file. We can copy the first line from one of the files you were given. 

```
file = open(file_list[0],'r')
title = file.readline()
print(title)
file.close()
```

We also need column labels. Note we need to add the end of line delimiter, the carriage-return and line-feed characters. We don't need to explicitly add them to `title` because there are already there, as we discovered in task 4.

```
column_labels = 'x, y1, y2, y3, y4, y5, y6\r\n'
```

In order to write a file, we must open it. As in the previous example, `file` is a file handle. The parameter `'w'` instructs Python to open the file for writing. If a file with this name already exsts, it will be overwritten (replaced). 
*Caution: If you had a gigabyte file containing your life's work, opened that file for writting in this way, then saved a single line "oops" to the file. Your life's work would be gone, replaced by "oops".*

The following code block writes the header. You will need to adapt the example in task 5 that displayed the first line of the data. Hint: `print()` displays the string to the screen, `file.write()` writes the string to the file. You will need to repeat `file. write()` in a for loop to write each line to the file in sequence. After that is done. Close the file. Open the file `consolidated_data.csv` from the sciserver file manager. It should look like you expect. If so, this exercise is complete!

```
file = open('consolidated_data.csv','w')
file.write(title)
file.write(column_labels)
file.close()
```

In [80]:
# Get Header From Previous File
file = open(file_list[0],'r')
title = file.readline()
print(title)
file.close()

# Set Column Names
column_labels = 'x, y1, y2, y3, y4, y5, y6\r\n'


# Write Header
file = open('consolidated_data.csv','w')
file.write(title)
file.write(column_labels)

# Task 5 with data size for the range
for ii in range(0,data_size[0]):
        file.write('{:5.1f},{:5.2f},{:5.2f},{:5.2f},{:5.2f},{:5.2f},{:5.2f}\r\n'.format(*out_data[ii,:]))
# Close File
file.close()


An exponentially decaying sine wave on a constant background



(95, 2)

# NOTES ON ARRAYS
## Arrays are a very powerful tools to work with data sets. Let's take a moment to look at some shorthand we can use to for the array indices. This is called *slicing.*

Concider an array `a`.  

Specify a consecutive range of elements:
> `a[start:stop]  # items start through stop-1`   
> `a[start:]      # items start through the rest of the array`  
> `a[:stop]       # items from the beginning through stop-1`  
> `a[:]           # a copy of the whole array` 

There is also the `step` value, which can be used with any of the above:
> `a[start:stop:step] # start through not past stop, by step` 

The key point to remember is that the `:stop` value represents the first value that is not in the selected slice. So, the difference between `stop` and `start` is the number of elements selected (if `step` is 1, the default).

The other feature is that `start` or `stop` may be a negative number, which means it counts from the end of the array instead of the beginning. So:
> `a[-1]    # last item in the array`  
> `a[-2:]   # last two items in the array`  
> `a[:-2]   # everything except the last two items`  

Similarly, `step` may be a negative number:
> `a[::-1]    # all items in the array, reversed`
> `a[1::-1]   # the first two items, reversed`
> `a[:-3:-1]  # the last two items, reversed`
> `a[-3::-1]  # everything except the last two items, reversed`  

Python is kind to the programmer when there are fewer items than you ask for. For example, if you ask for `a[:-2]` and `a` only contains one element, you get an empty list instead of an error. Sometimes you would prefer the error, so you have to be aware that this may happen.

As you learn more about the Python language, you will discover that these short cuts are an examples of the `range()` and `slice()` functions.